//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beecon.MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeeconDBEntities : DbContext
    {
        public BeeconDBEntities()
            : base("name=BeeconDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<FriendList> FriendLists { get; set; }
        public DbSet<Invite> Invites { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<TagPrivacyType> TagPrivacyTypes { get; set; }
        public DbSet<TagRating> TagRatings { get; set; }
        public DbSet<TagVisited> TagVisiteds { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
