//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beecon.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.TagRatings = new HashSet<TagRating>();
            this.TagVisiteds = new HashSet<TagVisited>();
            this.Categories = new HashSet<Category>();
        }
    
        public int TagID { get; set; }
        public string TagLongitude { get; set; }
        public string TagLatitude { get; set; }
        public string TagDescription { get; set; }
        public Nullable<System.DateTime> TagDateCreated { get; set; }
        public Nullable<System.DateTime> TagExpired { get; set; }
        public int UserID { get; set; }
        public string TagContent_URL { get; set; }
        public int PrivacyTypeID { get; set; }
    
        public virtual TagPrivacyType TagPrivacyType { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TagRating> TagRatings { get; set; }
        public virtual ICollection<TagVisited> TagVisiteds { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
    }
}
