//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beecon.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagVisited
    {
        public int VisitID { get; set; }
        public int UserID { get; set; }
        public int TagID { get; set; }
        public Nullable<System.DateTime> VisitTime { get; set; }
    
        public virtual Tag Tag { get; set; }
        public virtual User User { get; set; }
    }
}
