//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beecon.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.FriendLists = new HashSet<FriendList>();
            this.FriendLists1 = new HashSet<FriendList>();
            this.Invites = new HashSet<Invite>();
            this.Invites1 = new HashSet<Invite>();
            this.Tags = new HashSet<Tag>();
            this.TagRatings = new HashSet<TagRating>();
            this.TagVisiteds = new HashSet<TagVisited>();






        }
    
        public int UserID { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ZipCode { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string PasswordHashed { get; set; }
        public Nullable<int> TagsFound { get; set; }
        public Nullable<int> TagsPosted { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<FriendList> FriendLists { get; set; }
        public virtual ICollection<FriendList> FriendLists1 { get; set; }
        public virtual ICollection<Invite> Invites { get; set; }
        public virtual ICollection<Invite> Invites1 { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<TagRating> TagRatings { get; set; }
        public virtual ICollection<TagVisited> TagVisiteds { get; set; }
    }
}
