<?xml version="1.0" encoding="utf-8"?><Database Name="BeeconDB" Class="DataAccessDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=APPA105E16;Initial Catalog=BeeconDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BeeconDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblUser" Member="tblUsers">
    <Type Name="tblUser">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="Dob" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordHashed" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="TagsFound" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TagsPosted" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="tblUser_tblTag" Member="tblTags" ThisKey="UserID" OtherKey="UserID" Type="tblTag" />
    </Type>
  </Table>
  <Table Name="dbo.tblTag" Member="tblTags">
    <Type Name="tblTag">
      <Column Name="TagID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TagLongitude" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="TagLatitude" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="TagDescription" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="TagDateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TagExpired" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TagContent_URL" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="PrivacyTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblUser_tblTag" Member="tblUser" ThisKey="UserID" OtherKey="UserID" Type="tblUser" IsForeignKey="true" />
    </Type>
  </Table>
</Database>